// Mocks generated by Mockito 5.4.6 from annotations
// in green_stocks/test/bloc/portfolio_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:green_stocks/core/error/failures.dart' as _i5;
import 'package:green_stocks/features/portfolio/domain/entities/portfolio_stock.dart'
    as _i6;
import 'package:green_stocks/features/portfolio/domain/usecases/calculate_green_score.dart'
    as _i7;
import 'package:green_stocks/features/portfolio/domain/usecases/portfolio_usecases.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPortfolio].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPortfolio extends _i1.Mock implements _i3.GetPortfolio {
  MockGetPortfolio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PortfolioStock>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.PortfolioStock>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.PortfolioStock>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PortfolioStock>>>);
}

/// A class which mocks [AddToPortfolio].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddToPortfolio extends _i1.Mock implements _i3.AddToPortfolio {
  MockAddToPortfolio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call(
    String? symbol,
    double? quantity,
    double? purchasePrice,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            symbol,
            quantity,
            purchasePrice,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [
              symbol,
              quantity,
              purchasePrice,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}

/// A class which mocks [RemoveFromPortfolio].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFromPortfolio extends _i1.Mock
    implements _i3.RemoveFromPortfolio {
  MockRemoveFromPortfolio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call(String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [symbol],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}

/// A class which mocks [CalculateGreenScore].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateGreenScore extends _i1.Mock
    implements _i7.CalculateGreenScore {
  MockCalculateGreenScore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double call(List<_i6.PortfolioStock>? portfolio) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [portfolio],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  String band(double? score) => (super.noSuchMethod(
        Invocation.method(
          #band,
          [score],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #band,
            [score],
          ),
        ),
      ) as String);
}
